# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_info',
            field=models.TextField(default='An old english writer', max_length=1000, verbose_name='Author Info'),
            preserve_default=False,
        ),
    ]
