# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170922_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
